### ISSUE TITLE
[ENHANCE] Support multiple AssertionConsumerService properties in metadata

### ISSUE THREAD

**Issue by dertieran** [node-saml/node-saml#315]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to be able to add multiple `AssertionConsumerService` properties when generating the metadata.

**Describe the solution you'd like**
The `generateServiceProviderMetadata` should support passing multiple `callbackUrl`.
For backwards compatibility this could just mean supporting passing an `string[]` to `callbackUrl`.

**Comment by markstos** [comment]
@dertieran Please link to the part of the SAML spec that describes multiple AssertConsumerService properties being valid.

**Comment by dertieran** [comment]
@markstos Not to sure how I can best link this because it is a pdf but it is in the [metadata spec](https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf) under **2.4.4 Element <SPSSODescriptor>**

> <AssertionConsumerService> [One or More].
> One or more elements that describe indexed endpoints that support the profiles of the
> Authentication Request protocol defined in [SAMLProf]. All service providers support at least one
> such endpoint, by definition

**Comment by markstos** [comment]
Thank you @dertieran

**Comment by cjbarth** [comment]
As I read through the documentation that you've referenced and the other samples in that PDF, I don't see any support for multiple domains. As @srd90 pointed out in his [comment](https://github.com/node-saml/node-saml/pull/316#issuecomment-1683089697), this use-case isn't one we should support because it isn't the intended use-case for this feature.

For the correct way to handle this, see my [comment](https://github.com/node-saml/node-saml/pull/316#issuecomment-1683731724). Unless any PR related to this issue is scoped to handle adding HTTP Artifact along with multiple callback URLs, we can't accept it as there would be no valid use-case.
